<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://polytech.unice.fr/si/4a/isa/bf" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://webservices/" name="AffichageWebServiceImplService" targetNamespace="http://polytech.unice.fr/si/4a/isa/bf">
    <wsdl:import location="AffichageWSType.wsdl" namespace="http://webservices/">
    </wsdl:import>
    <wsdl:binding name="AffichageWebServiceImplServiceSoapBinding" type="ns1:AffichageWebService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="test">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="test">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="testResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="afficheWind">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="afficheWind">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="afficheWindResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="afficheTemperature">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="afficheTemperature">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="afficheTemperatureResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="afficheSnow">
            <soap:operation soapAction="" style="document"/>
            <wsdl:input name="afficheSnow">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="afficheSnowResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="AffichageWebServiceImplService">
        <wsdl:port binding="tns:AffichageWebServiceImplServiceSoapBinding" name="AffichageWebServiceImplPort">
            <soap:address location="http://localhost:8080/j2e-1.0-SNAPSHOT/webservices/AffichageWS"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>